### ISSUE TITLE
No option to install dependencies

### ISSUE THREAD

**Issue by CoreyCorza** [HugoTini/DeepBump#12]
![image](https://user-images.githubusercontent.com/40785775/223727462-9942da58-b39a-4665-9d19-b04e29ab1dce.png)

**Comment by CoreyCorza** [comment]
v5.1
Blender 3.4.1

**Comment by botroblowe** [comment]
I had to grab the DeepBump-master zip file as I installed only from v5.1

**Comment by HugoTini** [comment]
Seems to be the same issue as #15 and #16, should be fixed in v6, if not feel free to re-open a new issue

**Comment by CoreyCorza** [comment]
> Seems to be the same issue as #15 and #16, should be fixed in v6, if not feel free to re-open a new issue

Nice work!
