### ISSUE TITLE
Addon not showing up in toolbar

### ISSUE THREAD

**Issue by Gumbucks** [HugoTini/DeepBump#13]
Its installed and enabled but cant actually use it because its not available in the addon bar (next to "item, "tool", "view")

**Comment by HugoTini** [comment]
Could you try installing v6 and check if it works again ? If it still does not work, try to see if you can obtain any error msg/log from blender's console

**Comment by Gumbucks** [comment]
> Could you try installing v6 and check if it works again ? If it still does not work, try to see if you can obtain any error msg/log from blender's console

same problem still, didnt get any error messages either

**Comment by HugoTini** [comment]
Blender has two places where it can log issues :

- the info editor inside Blender
- the os terminal (depending on your OS, you might need to start blender from terminal to see it)

Make sure to check both of them to get error messages

**Comment by HugoTini** [comment]
Version v7 has a new approach for dependencies installation. On my side, it has been tested and works on :

- ✔ Linux, Blender 3.5, Portable (.tar.xz)
- ✔ Linux, Blender 3.5, Flatpak (Flathub)
- ✔ Linux, Blender 3.5, Snap
- ✔ Windows 10, Blender 3.5, Portable (.zip)
- ✔ Windows 10, Blender 3.5, Installer (.msi)
- ✔ Windows 10, Blender 3.5, Microsoft Store

The dependencies are now installed in the same folder as the addon, so removing the addon should also remove its dependencies (closing #14 ).

Open issues about deps install will be closed as either it should be solved, or, previously reported error logs won't be relevant to this new version.

In case there are still issue with the addon installation, feel free to open a new issue with :

- Operating System
- Blender installation method (Flatpak, Portable, Installer, MS Store, etc.)
- Blender error logs (in Blender Info Editor)
- Blender console logs (start Blender from a terminal)
- For windows, whereas Blender is running as admin or not
- Description of where the error occurs (while installing the addon, while installing the dependencies, addon not appearing in the shader editor right panel, error while computing the normal maps, etc.)
- Any other information that could be relevant

Before opening a new issue make sure you tried installing the latest version (v7) on a fresh & official Blender install.

thanks !
