### ISSUE TITLE
No documentation on removal/uninstallation

### ISSUE THREAD

**Issue by VGuerreiro** [HugoTini/DeepBump#14]
Hey there!
My laptop is a bit old and I just happened to try out DeepBump on it for the first time as it was the only pc I had in hand.
I am back to the office and have access to my desktop and installed it there already.
I wanted to clean up some space on the laptop and I'm not sure if removing the addon the normal way does remove everything it has installed.

Just wanted to know:
- what are these "Dependencies" the addon installs?
- where are these being installed by the addon?
- how do I get to remove those?
- please, this info should be in the docs imo...

**Comment by HugoTini** [comment]
Version v7 has a new approach for dependencies installation. On my side, it has been tested and works on :

- ✔ Linux, Blender 3.5, Portable (.tar.xz)
- ✔ Linux, Blender 3.5, Flatpak (Flathub)
- ✔ Linux, Blender 3.5, Snap
- ✔ Windows 10, Blender 3.5, Portable (.zip)
- ✔ Windows 10, Blender 3.5, Installer (.msi)
- ✔ Windows 10, Blender 3.5, Microsoft Store

The dependencies are now installed in the same folder as the addon, so removing the addon should also remove its dependencies (closing #14 ).

Open issues about deps install will be closed as either it should be solved, or, previously reported error logs won't be relevant to this new version.

In case there are still issue with the addon installation, feel free to open a new issue with :

- Operating System
- Blender installation method (Flatpak, Portable, Installer, MS Store, etc.)
- Blender error logs (in Blender Info Editor)
- Blender console logs (start Blender from a terminal)
- For windows, whereas Blender is running as admin or not
- Description of where the error occurs (while installing the addon, while installing the dependencies, addon not appearing in the shader editor right panel, error while computing the normal maps, etc.)
- Any other information that could be relevant

Before opening a new issue make sure you tried installing the latest version (v7) on a fresh & official Blender install.

thanks !

**Comment by Mesk911** [comment]
I join the question

**Comment by HugoTini** [comment]
A stated in the message above, the dependencies are now installed in the same folder as the addon. In the addon preference panel, there is an explicit message "_dependencies path :_" which clearly indicates this path.

The only two "root" dependencies are `numpy` and `onnxruntime`, however those might ofc have sub-dependencies. All installed dependencies can be seen in the addon folder.

**Comment by Mesk911** [comment]
@HugoTini You are telling "now", but I'm asking about previously installed dependencies (from the previous version of addon). Where are they stored?
