### ISSUE TITLE
ModuleNotFoundError after installing

### ISSUE THREAD

**Issue by kaydee001** [HugoTini/DeepBump#15]
Downloaded and installed v5.1, but while enabling the addon in preference, I encounter this error :

Traceback (most recent call last):
.\Blender 3.4\3.4\scripts\modules\addons_utils.py, line 333, in enable mod = __import__(module_name)
ModuleNotFoundError : No module named 'DeepBump-5'

Might be a Blender error or some error in the script.
Any help would be appreciated.
Thanks.

**Comment by Uzmen** [comment]
I have the exact same problem and couldn't find any solutions yet.
UPDATE: I tried to install 5.0 instead of 5.1 and it worked without any problem.

**Comment by HugoTini** [comment]
It should be fixed now in v6 (see [this comment](https://github.com/HugoTini/DeepBump/issues/16#issuecomment-1467197132))
