### ISSUE TITLE
Problem blender 3.4

### ISSUE THREAD

**Issue by ViannaFelipe** [HugoTini/DeepBump#17]
Does anyone know how to fix the dependency problem? I installed the latest version 6.0 of the addon in my blender 3.4, but I was not successful at all. Nothing about the addon appeared in blender. Even running as administrator and managing to install the dependencies.

**Comment by NeonBeacon** [comment]
Just downloaded Blender 3.5 and tried installing dependencies, the below error appears, any ideas?
![image](https://user-images.githubusercontent.com/129503880/229087720-2caf0254-35b1-4545-a1c4-daced26a28eb.png)

**Comment by HugoTini** [comment]
Version v7 has a new approach for dependencies installation. On my side, it has been tested and works on :

- ✔ Linux, Blender 3.5, Portable (.tar.xz)
- ✔ Linux, Blender 3.5, Flatpak (Flathub)
- ✔ Linux, Blender 3.5, Snap
- ✔ Windows 10, Blender 3.5, Portable (.zip)
- ✔ Windows 10, Blender 3.5, Installer (.msi)
- ✔ Windows 10, Blender 3.5, Microsoft Store

The dependencies are now installed in the same folder as the addon, so removing the addon should also remove its dependencies (closing #14 ).

Open issues about deps install will be closed as either it should be solved, or, previously reported error logs won't be relevant to this new version.

In case there are still issue with the addon installation, feel free to open a new issue with :

- Operating System
- Blender installation method (Flatpak, Portable, Installer, MS Store, etc.)
- Blender error logs (in Blender Info Editor)
- Blender console logs (start Blender from a terminal)
- For windows, whereas Blender is running as admin or not
- Description of where the error occurs (while installing the addon, while installing the dependencies, addon not appearing in the shader editor right panel, error while computing the normal maps, etc.)
- Any other information that could be relevant

Before opening a new issue make sure you tried installing the latest version (v7) on a fresh & official Blender install.

thanks !
