### ISSUE TITLE
Dependancy fail

### ISSUE THREAD

**Issue by CoreyCorza** [HugoTini/DeepBump#18]
When I installed the addon the other day, when you released v6, it fetched the dependencies fine. Everything installed fine. Everything was great.
Since then Ive updated to the latest blender v3.4.1 daily and tried to reinstall the addon and now the fetching of dependencies are failing

![blender_173cKbDdMe](https://user-images.githubusercontent.com/40785775/225519304-4185263a-bb34-4174-a4e6-1534b02119ab.png)

**Comment by HugoTini** [comment]
Looking at the error message, this might rather be a windows-related issue and not a Blender/Addon issue. 
Here some ideas you could try :

- Have shorter paths (have something like the official version with for e.g `/Download/blender-3.4.1-windows-x64` and not `/Downloads/blender-3.4.1-stable+v34.afsadjkfdsab-windows.amd64-release etc.`

or 

- Try this windows fix : https://stackoverflow.com/questions/71477633/the-filename-or-extension-is-too-long-while-installing-confluent-kafka/71672151#71672151 (might need a windows reboot before working)

**Comment by EcosystemNetwork** [comment]
Please help I have the same issue after upgrading to 3.4.1 and now 3.4 doesn't work anymore, Both your suggestions don't work :(

**Comment by HugoTini** [comment]
Version v7 has a new approach for dependencies installation. On my side, it has been tested and works on :

- ✔ Linux, Blender 3.5, Portable (.tar.xz)
- ✔ Linux, Blender 3.5, Flatpak (Flathub)
- ✔ Linux, Blender 3.5, Snap
- ✔ Windows 10, Blender 3.5, Portable (.zip)
- ✔ Windows 10, Blender 3.5, Installer (.msi)
- ✔ Windows 10, Blender 3.5, Microsoft Store

The dependencies are now installed in the same folder as the addon, so removing the addon should also remove its dependencies (closing #14 ).

Open issues about deps install will be closed as either it should be solved, or, previously reported error logs won't be relevant to this new version.

In case there are still issue with the addon installation, feel free to open a new issue with :

- Operating System
- Blender installation method (Flatpak, Portable, Installer, MS Store, etc.)
- Blender error logs (in Blender Info Editor)
- Blender console logs (start Blender from a terminal)
- For windows, whereas Blender is running as admin or not
- Description of where the error occurs (while installing the addon, while installing the dependencies, addon not appearing in the shader editor right panel, error while computing the normal maps, etc.)
- Any other information that could be relevant

Before opening a new issue make sure you tried installing the latest version (v7) on a fresh & official Blender install.

thanks !
