### ISSUE TITLE
Dependency fail on blender 3.4 for ubuntu 22.04.

### ISSUE THREAD

**Issue by K1nyash** [HugoTini/DeepBump#19]
Command '['/snap/blender/3132/3.4/python/bin/python3.10', '-m', 'pip', 'install', 'onnxruntime']' returned non-zero exit status 1.
![image](https://user-images.githubusercontent.com/110404458/226185568-b3fb6072-d893-4fd8-8dbc-d8e75ca503a8.png)

Been stuck here for a while... is there a way to use the terminal to install them like in dream textures...though i have tried to open the deepmap_master file on terminal and install onnxruntime there but to no avail.

**Comment by Vertexbrush** [comment]
![image](https://user-images.githubusercontent.com/125984057/228148541-54165e48-b1f1-478e-90b7-cd44931aa099.png)
![image](https://user-images.githubusercontent.com/125984057/228148655-a5015a79-4819-4426-a4b0-eaeeb68018a8.png)

+1 for this issue, Also I'm on windows and using Blender 3.4.1

**Comment by Vertexbrush** [comment]
okay my bad but seems this issue is solved by the solution you gave here:
https://github.com/HugoTini/DeepBump/issues/4#issuecomment-1328297037

At least in my case it was an admin privileges issue, its working now

**Comment by K1nyash** [comment]
When i run the blender from terminal i dont find any of the insttalled add ons but i want to create a blender specific environment and try it again. glad u got it solved @Vertexbrush

**Comment by K1nyash** [comment]
So it resolved itself when blender updated to version 3.5 ... now usable ...thanks for the great works.
