### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)

### ISSUE THREAD

**Issue by Ulf3000** [HugoTini/DeepBump#2]
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none) .. trying to intall manually gives the same error , importing pip in script gives same error

**Comment by HugoTini** [comment]
It works on Blender 3.0, but I can indeed reproduce the issue on 3.1.

Blender 3.0 is using python 3.9 while Blender 3.1 is using python 3.10 which might be causing the same issue as [here](https://github.com/microsoft/onnxruntime/issues/11332). It should be fixed once Microsoft releases `onnxruntime` for python 3.10

**Comment by HugoTini** [comment]
Installation is working again, closing the issue
