### ISSUE TITLE
Blender 3.5 dependecie installed but not showng in the menu

### ISSUE THREAD

**Issue by zanshinfx** [HugoTini/DeepBump#21]
Dependencies are installed (with the message) but stil have the warning that is not

**Comment by zanshinfx** [comment]
I decided to do a clean install to see in the console what message I've got:

Collecting onnxruntime
  Using cached onnxruntime-1.14.1-cp310-cp310-win_amd64.whl (6.5 MB)
Collecting protobuf
  Using cached protobuf-4.22.1-cp310-abi3-win_amd64.whl (420 kB)
Collecting coloredlogs
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting sympy
  Using cached sympy-1.11.1-py3-none-any.whl (6.5 MB)
Collecting flatbuffers
  Using cached flatbuffers-23.3.3-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: numpy>=1.21.6 in c:\program files\blender foundation\blender 3.5\3.5\python\lib\site-packages (from onnxruntime) (1.23.5)
Collecting packaging
  Using cached packaging-23.0-py3-none-any.whl (42 kB)
Collecting humanfriendly>=9.1
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting pyreadline3
  Using cached pyreadline3-3.4.1-py3-none-any.whl (95 kB)
Installing collected packages: pyreadline3, mpmath, flatbuffers, sympy, protobuf, packaging, humanfriendly, coloredlogs, onnxruntime
  WARNING: The script isympy.exe is installed in 'C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script humanfriendly.exe is installed in 'C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script coloredlogs.exe is installed in 'C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script onnxruntime_test.exe is installed in 'C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed coloredlogs-15.0.1 flatbuffers-23.3.3 humanfriendly-10.0 mpmath-1.3.0 onnxruntime-1.14.1 packaging-23.0 protobuf-4.22.1 pyreadline3-3.4.1 sympy-1.11.1


But stil the same :
![image](https://user-images.githubusercontent.com/129772663/229573514-0cc313a9-ca4e-4c72-860f-cf66b56e7b42.png)

**Comment by HugoTini** [comment]
The warning message is static, it does not change depending on whereas the dependencies are installed or not.
(Maybe it could be changed to something like "_Make sure dependencies are installed in the preference panel below_" to make it clearer)

This is why there is then a ✔ _Dependencies are installed_  message in the panel below to confirm everything is ok.

Since you have `Successfully installed onnxruntime-1.14.1` in your logs, the addon should work. Does it appear in the shader editor right panel ?

**Comment by zanshinfx** [comment]
Hi Hugo thank you for your help. Yes the dependencies are installed in the proper folder, but as you ask it does not appear in the shader right panel. I also try to make a different path in the script panel whitout any change. To add info I was with Blender 3.4.1 before with same result, it means it as nothing to do with the Blender version

**Comment by HugoTini** [comment]
Version v7 has a new approach for dependencies installation. On my side, it has been tested and works on :

- ✔ Linux, Blender 3.5, Portable (.tar.xz)
- ✔ Linux, Blender 3.5, Flatpak (Flathub)
- ✔ Linux, Blender 3.5, Snap
- ✔ Windows 10, Blender 3.5, Portable (.zip)
- ✔ Windows 10, Blender 3.5, Installer (.msi)
- ✔ Windows 10, Blender 3.5, Microsoft Store

The dependencies are now installed in the same folder as the addon, so removing the addon should also remove its dependencies (closing #14 ).

Open issues about deps install will be closed as either it should be solved, or, previously reported error logs won't be relevant to this new version.

In case there are still issue with the addon installation, feel free to open a new issue with :

- Operating System
- Blender installation method (Flatpak, Portable, Installer, MS Store, etc.)
- Blender error logs (in Blender Info Editor)
- Blender console logs (start Blender from a terminal)
- For windows, whereas Blender is running as admin or not
- Description of where the error occurs (while installing the addon, while installing the dependencies, addon not appearing in the shader editor right panel, error while computing the normal maps, etc.)
- Any other information that could be relevant

Before opening a new issue make sure you tried installing the latest version (v7) on a fresh & official Blender install.

thanks !
