### ISSUE TITLE
dependencies don't install on blender 3.5

### ISSUE THREAD

**Issue by RiceWitch** [HugoTini/DeepBump#22]
Command '['C:\\Program Files\\Blender Foundation\\Blender 3.5\\3.5\\python\\bin\\python.exe', '-m', 'pip', 'install', 'onnxruntime']' returned non-zero exit status 1.
It seems I'm the only one having the issue.

**Comment by RiceWitch** [comment]
different error comes up when I disable it
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 421, in disable
    mod.unregister()
  File "C:\Users\emmet\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\DeepBump-6\__init__.py", line 497, in unregister
    del bpy.types.Scene.deep_bump_tool
AttributeError: deep_bump_tool

**Comment by RiceWitch** [comment]
I even re-installed the addon and python and have the windows longer code thing on 1

**Comment by RiceWitch** [comment]
figured out you have to run blender as administrator, no idea why only one person brought it up in a previous thread.

**Comment by HugoTini** [comment]
It is written in the readme that you should try running as admin in case of problem

**Comment by sultansairam** [comment]
Even if run as the admin, I get the same error as : 

![image](https://user-images.githubusercontent.com/88925344/230723052-0618a7ef-8434-459c-a6c9-f169d77c98cf.png)

I also reset the PC and installed python 3.11.3 v along with PIP. But no use. Please help ASAP
