### ISSUE TITLE
Update for 3.1?

### ISSUE THREAD

**Issue by melvixiodf** [HugoTini/DeepBump#3]
Hi, Awesome work with this very powerful addon. Any chance for an update for 3.1?

Thanks for making this available for free to other artists.

Cheers,

**Comment by HugoTini** [comment]
Hello, thanks for the kind words, glad to hear the addon is useful to you ! As mentioned [here](https://github.com/HugoTini/DeepBump/issues/2), there is an issue with Blender 3.1 but it should be fixed automatically once `onnxruntime` is released for python 3.10.

**Comment by melvixiodf** [comment]
Ok. Thanks. 
Keep up the great work.

Btw, any chance you could add the ability to generate a shadow/ao  removed albedo map to the addon? Is this possible with AI training? Love the results generated from the albedo map with shadows. Very realistic.

I also use the Generate height from Normal map addon as well.

**Comment by HugoTini** [comment]
Generating an AO map can be done by displacing a plane using the heightmap and baking the AO with Cycles.

<details>
  <summary>Example</summary>
  
  An example of the original photo, DeepBump's normal, NormalHeight's height & Cycles' baked AO from height :
  ![maps](https://user-images.githubusercontent.com/65409496/176037770-983c0e2a-6220-4c9b-86c9-ff77ff124d97.png)
</details>


Now "delighting" the albedo from GI + hard & soft shadows is a whole research field with several approaches (Machine Learning, Differential rendering, etc.), that's for sure an interesting topic to work on if time would allow, but currently the addon has no such feature.

If you don't have hard shadows, one possible trick is to use the generated heightmap (and/or the AO map), invert it and blend it on the original picture in any image editor.

<details>
  <summary>Example</summary>

  ![flat](https://user-images.githubusercontent.com/65409496/176037922-b844a6c6-a998-430c-adb0-b6ef3e640f91.png)
</details>

Back to the original issue, it should be solved with the next version of `onnxruntime` which is coming out [mid-july](https://github.com/microsoft/onnxruntime/projects?type=classic)

**Comment by melvixiodf** [comment]
Thanks for the examples. Very very Helpful.

> Back to the original issue, it should be solved with the next version of `onnxruntime` which is coming out [mid-july](https://github.com/microsoft/onnxruntime/projects?type=classic)

That's great news. Thanks a ton.

**Comment by Trass3r** [comment]
It took some fiddling to install it manually:
```sh
3.2\python\bin\python.exe -m pip install flatbuffers sympy coloredlogs numpy==1.23.1
3.2\python\bin\python.exe -m pip install -i https://test.pypi.org/simple/ ort-nightly==1.12.0.dev20220711001
```

**Comment by HugoTini** [comment]
I have checked with Blender 3.2 today and it now installs without any issue
