### ISSUE TITLE
Generate Buttons greyed out. and Unable to remove addon even when running blender as administrator

### ISSUE THREAD

**Issue by StoneSymmetry** [HugoTini/DeepBump#38]
Im Always getting this error when trying to remove the addon.

PermissionError: [WinError 5] Access is denied: 'C:\\Users\\green\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons\\DeepBump-7\\onnxruntime\\capi\\onnxruntime_providers_shared.dll'
Error: Python: Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\green\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons\\DeepBump-7\\onnxruntime\\capi\\onnxruntime_providers_shared.dll'

Few times when I tried to install the Dependencies, and I got an error about import onnxruntime? or something and how it wasn't there, But when tried  to install it with cmd it was there already..
 

I have Blender on Steam, and this worked just fine on my older PC. Does this not work on Windows 11 or something? it's been really frustrating!

**Comment by hirenumradia** [comment]
@StoneSymmetry How did you manage to fix this? Im getting 

`When installing the addon and trying to enable it im getting "File "G:\Program Files\Blender Foundation\Blender 4.3\4.3\python\Lib\site-packages\onnxruntime\__init__.py", line 61, in <module>
raise import_capi_exception
File "G:\Program Files\Blender Foundation\Blender 4.3\4.3\python\Lib\site-packages\onnxruntime\__init__.py", line 24, in <module>
from onnxruntime.capi._pybind_state import (
File "G:\Program Files\Blender Foundation\Blender 4.3\4.3\python\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
from .onnxruntime_pybind11_state import * # noqa
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing onnxruntime_pybind11_state: A dynamic link library (DLL) initialization routine failed."`

**Comment by StoneSymmetry** [comment]
Its been so long I cant really remember how I fixed it..
Is python up to date?

**Comment by hirenumradia** [comment]
I fixed it by going to the Python console within Blender, uninstalling "onnxruntime," and installing an older version.
