### ISSUE TITLE
Error when installing dependencies

### ISSUE THREAD

**Issue by eyemcreative** [HugoTini/DeepBump#4]
When I try to install the dependencies, it loads for a second and then gives me this error:
Command '['C:\\Program Files\\Blender Foundation\\Blender 3.2\\3.2\\python\\bin\\python.EXE', '-m', 'pip', 'install', 'onnxruntime']' returned non-zero exit status 1.

I can't find any documentation or anyone else talking about this error

**Comment by Globberbob** [comment]
I am also having this issue.
I tried installing DeepBump, and when I clicked the button to get the dependencies this same error occurred. As far as I can find there is no current solution still

**Comment by PhiMue86** [comment]
Run Blender as Administrator.

**Comment by HugoTini** [comment]
It seems that on Windows, depending how Blender was installed, it can happen that the script doesn't get sufficient permissions to install the dependencies. 

As mentioned by @FeuerTiger86, it should work by running Blender as admin (right click on Blender in Windows' menu -> _run as administrator_). I've updated the readme to mention this. Note that this is just needed for installing dependencies, then Blender can be run normally again
