### ISSUE TITLE
DeepBump as Command-Line Program

### ISSUE THREAD

**Issue by fuchsundvogel** [HugoTini/DeepBump#5]
Hey HugoTini,
on your blog post about DeepBump it is stated that 'This tool is available both as a Blender add-on and as a command-line program.'

Unfortunately I was unable to find any further information about the 'command-line program' anywhere. All repository content seems to be the blender add-on only. Can you give any hints about how to use DeepBump without blender? Or is that just not easily possible right now?

Thank you very much!

**Comment by DriesDeRidder** [comment]
Yeah having the same problem. I don't really have python experience so getting this to work is kinda hard. Any tips?

**Comment by HugoTini** [comment]
Hi ! Indeed, there used to be a CLI, but wasn't kept in the last refactoring. If this is still wanted, then we should bring it back

**Comment by DriesDeRidder** [comment]
Yeah I would still like to have it implemented :)

**Comment by EnviralDesign** [comment]
yeah thinking the cli option is as must have! love that you integrated it so nicely in to blender, but cli is super important to integration into other pipelines.

**Comment by HugoTini** [comment]
The latest version adds a terminal CLI, see [cli.md](https://github.com/HugoTini/DeepBump/blob/master/cli.md). If there is any issue with it, feel free to open a new issue
